// <auto-generated />
namespace LSDS.CTM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MovedSettlementTransactionConditionIndicator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovedSettlementTransactionConditionIndicator));
        
        string IMigrationMetadata.Id
        {
            get { return "201511112341268_Moved SettlementTransactionConditionIndicator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
